# Generated by Django 3.2.7 on 2022-02-12 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Restaurent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('datetimemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Restaurent.datetimemixin')),
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
            ],
            bases=('Restaurent.datetimemixin',),
        ),
        migrations.RenameModel(
            old_name='Restaurent',
            new_name='Restaurant',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('datetimemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Restaurent.datetimemixin')),
                ('status', models.CharField(choices=[('Delivered', '1')], max_length=100)),
                ('dish_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Restaurent.dish')),
                ('restaurant_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Restaurent.restaurant')),
            ],
            bases=('Restaurent.datetimemixin',),
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Restaurent.restaurant'),
        ),
    ]
