# Generated by Django 3.2.7 on 2022-02-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurent', '0002_auto_20220212_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Delivered'), ('2', 'Placed'), ('3', 'Accepted'), ('4', 'Rejected')], default='2', max_length=100),
        ),
    ]
