# Generated by Django 3.2.7 on 2022-02-12 04:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Restaurent', '0004_auto_20220212_0454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='Restaurent',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='restaurant_key',
            new_name='restaurent_key',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='restaurant_key',
            new_name='restaurent_key',
        ),
    ]
