# Generated by Django 3.2.7 on 2022-02-12 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurent', '0006_auto_20220212_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('datetimemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Restaurent.datetimemixin')),
                ('status', models.CharField(max_length=200)),
            ],
            bases=('Restaurent.datetimemixin',),
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
